language: python

os: linux
dist: focal

git:
  depth: 3
  quiet: true

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libzstd-dev g++

install:
  - test indexed_zstd/indexed_zstd.cpp -nt indexed_zstd/indexed_zstd.pyx ||
    echo -e '\e[31mPlease trigger a rebuild of indexed_zstd.pyx using "python3 setup.py build_ext --inplace --cython" and commit the new file\e[0m'
  - pip install --upgrade cython twine
  - python3 setup.py build_ext --inplace --cython

script:
  # test whether installation from tarball works
  - python3 setup.py sdist
  - twine check dist/*
  - pip install dist/*.tar.gz
  # test zstd decoder
  #- python3 test/test.py

env:
  global:
    # travis encrypt TWINE_PASSWORD=...
    - secure: "f0DEWuHpbspIe8/UNnwHpk2vQPXAfXutts60FVa3TMKOjktz/VQVtZ7M5nsXApnX4xPtf3+w8eqpWG1QVTAg0dQqABcDsvgTpqV4mliE61GJCaYYQl/Q0o+oMrzS0y76LMVucWYepWMWW+FFfrtUDEJxKOVFyTWE35RqyHmWcI45Ope6Sn+xQh0KHMJqV2hRuC2g88xeYFkGx+4CoqrjfNZqHSuK6Ru6P3Ol8mq7Nnf9wq75HtSAZRawnPVJY3hwIc/4TeIy3UUAIFHojiVKhiRTNMdbNIC00BYxof+lcI6gnE6V5Mdmr6UJOfgVG9IL9TSiHJJ3WQx/M03vYZT9YNu3G9v7ukcHXSfKCUXtz3ZCh3A+Ed9COd4GcoYlCBfb1g28khVdKDInDZSH8PObcMJO9VWw6b/bInJBuuKGs6OC73Lk8gUT2/ANN1I4qZkzVYVcqjbooVZdlI8rSCdyzh9wzO9a+Rm2ov+NZp28hb44TWHFH1vD8ZVJLlOQmHnjMWeQSDXAxLsbb1s44tu7ZVmu17JHIsRkQrJVoLUw/seodUOFrtL9Kw+3viSqoAq2PxWsm7J22eWhzCFUV43iWHb1GnV3LWvVA4F9E6gEEw6WSf0amAdW6XK6FPQO1FrNnGaWqehsNyS2HQlp2ePsGMs47aPWEyBb1VlUBZ9k/t4="

jobs:
  include:
    - name: build-tarball
      stage: deploy
      script:
        - python3 setup.py sdist
        - twine check dist/*
        - twine upload --skip-existing -u __token__ dist/*

    - name: build-manylinux2010_x86_64
      stage: deploy
      services:
        - docker
      script:
        - docker run --rm -v "$( pwd ):/project" quay.io/pypa/manylinux2010_x86_64 bash /project/manylinux/build-wheels.sh manylinux2010_x86_64
        - twine check dist/*
        - twine upload --skip-existing -u __token__ dist/*

    - name: build-manylinux2014_x86_64
      stage: deploy
      services:
        - docker
      script:
        - docker run --rm -v "$( pwd ):/project" quay.io/pypa/manylinux2014_x86_64 bash /project/manylinux/build-wheels.sh manylinux2014_x86_64
        - twine check dist/*
        - twine upload --skip-existing -u __token__ dist/*

stages:
  - name: test
    # test with: travis-conditions eval "..." --data '{ "commit_message": "test string" }'
    # after installing: gem install --user-install travis-conditions
    if: NOT ( commit_message =~ /(^|[^A-Za-z])[Ww][Ii][Pp]([^A-Za-z]|$)/ )
  - name: deploy
    if: tag =~ /^v/
